// ModbusSetup.h
#ifndef MODBUS_SETUP_H
#define MODBUS_SETUP_H

#include <Arduino.h>
#include <ModbusRTU.h>

#define SLAVE_ID 2
#define NUM_REGS 3000
#define DE_RE_PIN 16  // Define the pin for DE and RE
#define TX_PIN 17
#define RX_PIN 18

#define TX_PIN_DEV 43
#define RX_PIN_DEV 44

//Register from SDM720-M
#define PHASE_1_LINE_TO_NEUTRAL_VOLTS 1
#define PHASE_2_LINE_TO_NEUTRAL_VOLTS 3
#define PHASE_3_LINE_TO_NEUTRAL_VOLTS 5
#define PHASE_1_CURRENT 7
#define PHASE_2_CURRENT 9
#define PHASE_3_CURRENT 11
#define PHASE_1_ACTIVE_POWER 13
#define PHASE_2_ACTIVE_POWER 15
#define PHASE_3_ACTIVE_POWER 17
#define PHASE_1_APPARENT_POWER 19
#define PHASE_2_APPARENT_POWER 21
#define PHASE_3_APPARENT_POWER 23
#define PHASE_1_REACTIVE_POWER 25
#define PHASE_2_REACTIVE_POWER 27
#define PHASE_3_REACTIVE_POWER 29
#define PHASE_1_POWER_FACTOR 31
#define PHASE_2_POWER_FACTOR 33
#define PHASE_3_POWER_FACTOR 35
#define AVERAGE_LINE_TO_NEUTRAL_VOLTS 43
#define AVERAGE_LINE_CURRENT 47
#define SUM_OF_LINE_CURRENTS 49
#define TOTAL_SYSTEM_POWER 53
#define TOTAL_SYSTEM_VOLT_AMPS 57
#define TOTAL_SYSTEM_VAR 61
#define TOTAL_SYSTEM_POWER_FACTOR 63
#define FREQUENCY_OF_SUPPLY_VOLTAGES 71
#define IMPORT_ACTIVE_ENERGY 73
#define EXPORT_ACTIVE_ENERGY 75
#define LINE_1_TO_LINE_2_VOLTS 201
#define LINE_2_TO_LINE_3_VOLTS 203
#define LINE_3_TO_LINE_1_VOLTS 205
#define AVERAGE_LINE_TO_LINE_VOLTS 207
#define NEUTRAL_CURRENT 225
#define TOTAL_ACTIVE_ENERGY 343
#define TOTAL_REACTIVE_ENERGY 345
#define RESETTABLE_TOTAL_ACTIVE_ENERGY 385
#define RESETTABLE_TOTAL_REACTIVE_ENERGY 387
#define RESETTABLE_IMPORT_ACTIVE_ENERGY 389
#define RESETTABLE_EXPORT_ACTIVE_ENERGY 391
#define NET_KWH_IMPORT_EXPORT 397
#define TOTAL_IMPORT_ACTIVE_POWER 1281
#define TOTAL_EXPORT_ACTIVE_POWER 1283

extern ModbusRTU rtu_mb;

void init_Modbus_Rtu();
void RTUputCharToBuf(uint16_t value,uint16_t reg);
uint16_t RTUgetCharFromBuf(uint16_t reg);
void RTUputFloatToBuf(float value, uint16_t start_reg);
float RTUgetFloatFromBuf(uint16_t start_reg);

#endif // MODBUS_SETUP_H
